default: &default
  adapter: postgresql
  encoding: unicode
  database: mus_app_final
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  database: mus_app_final
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: mus_app_final

production:
  <<: *default
  database: mus_app_final_production
  username: mus_app_final
  password: <%= ENV["MUSAPP_DATABASE_PASSWORD"] %>
